<?php
// Generated by ZF2's ./bin/classmap_generator.php @ Tue, 24 Jan 2012 16:52:03 +0100
return array(
    'EMT\Client\Client'                     => __DIR__ . '/library/EMT/Client/Client.php',
    'EMT\Client\Exception\Conflict'         => __DIR__ . '/library/EMT/Client/Exception/Conflict.php',
    'EMT\Client\Exception\ConnectionFailed' => __DIR__ . '/library/EMT/Client/Exception/ConnectionFailed.php',
    'EMT\Client\Exception\NotFound'         => __DIR__ . '/library/EMT/Client/Exception/NotFound.php',
    'EMT\Client\Exception\NotImplemented'   => __DIR__ . '/library/EMT/Client/Exception/NotImplemented.php',
    'EMT\Client\Exception\ServerError'      => __DIR__ . '/library/EMT/Client/Exception/ServerError.php',
    'EMT\Client\Exception\TooManyRequests'  => __DIR__ . '/library/EMT/Client/Exception/TooManyRequests.php',
    'EMT\Client\Exception\Unauthorized'     => __DIR__ . '/library/EMT/Client/Exception/Unauthorized.php',
    'EMT\Client\Exception'                  => __DIR__ . '/library/EMT/Client/Exception.php',
    'EMT\Client\Request'                    => __DIR__ . '/library/EMT/Client/Request.php',
    'EMT\Client\Response'                   => __DIR__ . '/library/EMT/Client/Response.php',
    'EMT\Exception'                         => __DIR__ . '/library/EMT/Exception.php',
    'EMT\Model\AbstractModel'               => __DIR__ . '/library/EMT/Model/AbstractModel.php',
    'EMT\Model\Media'                       => __DIR__ . '/library/EMT/Model/Media.php',
    'EMT\Model\Product'                     => __DIR__ . '/library/EMT/Model/Product.php',
);